- name: 'API Changes'
  color: '56e2e9'
- name: 'DJS Changes'
  color: '56e2e9'
- name: 'type: discussion'
  color: 'ffffff'
- name: 'type: enhancement'
  color: 'f6fa1b'
- name: 'type: bug'
  color: 'fa1b3c'
- name: 'type: bugfix'
  color: 'fa1b3c'
- name: 's: duplicate'
  color: 'D4C5F9'
- name: 's: already fixed'
  color: 'D4C5F9'
- name: 's: won''t fix'
  color: 'D4C5F9'
- name: 's: unverified'
  color: 'D4C5F9'
- name: 'type: question (please use Discord instead)'
  color: 'd876e3'
- name: 'semver: major'
  color: 'c10f47'
- name: 'semver: minor'
  color: 'e4f486'
- name: 'semver: patch'
  color: 'e8be8b'
- name: 'priority: high'
  color: '37140A'
- name: 'priority: medium'
  color: 'D8DF63'
- name: 'priority: low'
  color: '02E6AD'
- name: 'update: npm'
  color: '1b99fa'
- name: 'meta: documentation'
  color: 'FBCA04'
- name: 's: approved'
  color: '49eb34'
- name: 's: awaiting review'
  color: 'ed6432'
- name: 's: has PR'
  color: 'f9d0c4'